version: "3"

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${pg_user}
      - POSTGRES_PASSWORD=${pg_passwd}
      - POSTGRES_DB=${pg_db}
    volumes:
      - ./docker-postgres.sh:/docker-entrypoint-initdb.d/docker-postgres.sh
      - dbdata:/var/lib/postgresql/data/

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    ports:
      - 10001:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=${nc_pg_host}
      - POSTGRES_USER=${nc_pg_user}
      - POSTGRES_PASSWORD=${nc_pg_passwd}
      - POSTGRES_DB=${nc_pg_db}
      - NEXTCLOUD_ADMIN_USER=${nc_admin_name}
      - NEXTCLOUD_ADMIN_PASSWORD=${nc_admin_passwd}
    depends_on:
      - db

  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux
    ports:
      - 10002:8080
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${mf_pg_user}:${mf_pg_passwd}@${mf_pg_host}/${mf_pg_db}?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${mf_admin_name}
      - ADMIN_PASSWORD=${mf_admin_passwd}

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    depends_on:
      - db
    restart: always
    volumes:
      - vwdata:/data
    ports:
      - 10003:80
    environment:
      - LOG_FILE=/data/vaultwarden.log
      - DATABASE_URL=postgresql://${vw_pg_user}:${vw_pg_passwd}@${vw_pg_host}/${vw_pg_db}
      - ADMIN_TOKEN=${vw_admin_token}

volumes:
    nextcloud:
    vwdata:
    dbdata:
